<?xml version="1.0" encoding="utf-8"?><Database Name="EnergyMonitor" Class="DB_MVCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.131.200.70;Initial Catalog=EnergyMonitor;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EnergyMonitorConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AnalogHistory" Member="AnalogHistories">
    <Type Name="AnalogHistory">
      <Column Name="AH_AnalogNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AH_Time" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AH_Value" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AnalogInfo" Member="AnalogInfos">
    <Type Name="AnalogInfo">
      <Column Name="RTU_No" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="AI_No" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AI_Serial" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AI_Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AI_LogicalLow" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AI_LogicalUp" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AI_Decimal" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AI_Cptflag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AI_Base" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AI_Rate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AI_LockVal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AI_LockFlag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AI_Timespace" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AI_Unit" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AI_State" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AI_Level" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="AI_Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AnalogMeasurePoint" Member="AnalogMeasurePoints">
    <Type Name="AnalogMeasurePoint">
      <Column Name="AMP_AnalogNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AMP_Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AMP_CptFlag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AMP_Statistic" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AMP_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AMP_Val" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AMP_ValRem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AMP_Unit" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AMP_SchooldID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMP_SAreaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMP_BuildingID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMP_RoomID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMP_DepartID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMP_PowerType" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AMP_PowerName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AMP_Timespan" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="AMP_ParentNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMP_OperationRule" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AMP_OperationParameter" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AMP_State" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AMP_Encoding" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuildingBriefInfo" Member="BuildingBriefInfos">
    <Type Name="BuildingBriefInfo">
      <Column Name="BDI_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BDI_Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SAI_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BDI_Flag" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="BDI_HJFlag" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="BDI_OperateRule" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PowerClass" Member="PowerClasses">
    <Type Name="PowerClass">
      <Column Name="PC_ID" Type="System.String" DbType="VarChar(500) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PC_Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="PC_Type" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="PC_LocalCode" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="PC_Unit" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="PC_Remark" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RoomInfo" Member="RoomInfos">
    <Type Name="RoomInfo">
      <Column Name="RI_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RI_SerialCode" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RI_RoomCode" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="BDI_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RI_Floor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RI_Remark" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RI_LogOperator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RI_CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RI_UpdateOperator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RI_UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RTU" Member="RTUs">
    <Type Name="RTU">
      <Column Name="RTU_No" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RTU_Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RTU_Info" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RTU_MaxAI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RTU_MaxDI" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RTU_State" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RTU_WSNO" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RTU_ChanSerial" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RTU_Serial" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="RTU_StaNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolAreaInfo" Member="SchoolAreaInfos">
    <Type Name="SchoolAreaInfo">
      <Column Name="SAI_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SI_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SAI_Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SAI_Remark" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolInfo" Member="SchoolInfos">
    <Type Name="SchoolInfo">
      <Column Name="SI_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SI_Code" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SI_Name" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SI_Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SI_Remark" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="SI_LogOperator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SI_CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SI_UpdateOperator" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SI_UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SI_BuildingArea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SI_GroudArea" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>